name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: "Node ${{ matrix.node }} / ${{ matrix.os }}"
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [20.x, 22.x]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Run test
        run: |
          npm ci
          npm test
